### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by gaborka98** [Teaching-projects/SZE-MoSzE-2019-Tristania#8]
Szia Máté!
olyan kérdésünk van, hogy ha github pagesre akarjuk kitenni a doxygent, akkor azt irja ahhoz uj repot kell csinálni. Ezt hogyan tudjuk megoldani? Órán említetted, hogy issue és akkor megcsináljátok, de nem emlékszek, hogy konkrétan erre mondtad-e. egy külön brachet leágaztattam Doxygen néven azt hiszem, de ebben sem vagyok biztos, hogy az most kellett volna. Mondjuk annyira jo lesz ha nem kellett volna, hogy külön abba írom bele a circleci-os részt és elválik.
Előre is köszi a választ.

**Comment by hegyhati** [comment]
Ooo, most akkor ez megoldodott? En azt javasoltam, hogy ne uj repo, hane mcsak egy uj branch legyen, de ne az aktualisbol, hanem az elso committol, es oda pusholjatok.

**Comment by hegyhati** [comment]
Amihez en kellek, az a github pages beallitasa, amit most mindjart meg is teszek akkor Nektek.

**Comment by hegyhati** [comment]
Illetve mar be van, akkor ezek szerint megsem kellettem en.

**Comment by gaborka98** [comment]
Igen közben én is rájöttem, hogy nem kell uj repo csak egy uj brach elég meg is csináltam pont most a gh-pages brachet. majd erre teszi elvileg a circleci
